require("user.keymaps")
require("user.plugins")
require("user.autocommands")
require("user.colorscheme")
require("user.cmp")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
require("user.nvim-tree")
require("user.lualine")
require("user.toggleterm")
require("user.impatient")
require("user.illuminate")
require("user.alpha")
require("user.lsp")
--[[ require("user.whichkey") ]]
require("user.options")
--[[ require("user.emmet") ]]
require("user.colorizer")
require("user.quickscope")
require("user.snippets")
